<?php require_once 'templates/header.phtml' ?>

<form action="agregarartista" method="POST">
    <input required type="text" name="artist" placeholder="Ingrese nombre del artista">
    <input required type="date" name="dob" placeholder="Ingrese fecha de nacimiento">
    <input required type="text" name="pob" placeholder="Ingrese país de nacimiento">
    <button type="submit">Agregar album</button>
</form>