<?php require_once 'templates/header.phtml' ?>

<form action="agregardisco" method="POST">
    <input required type="text" name="album" placeholder="Ingrese título del disco">
    <input required type="date" name="dor" placeholder="Ingrese fecha de lanzamiento">
    <input required type="number" name="id_artist" placeholder="Ingrese ID de artista">
    <input required type="time" name="duration" placeholder="Ingrese largo del disco">
    <button type="submit">Agregar album</button>
</form>