<?php require_once 'header.phtml'?>

<ul class="list-group">
    <li class="list-group-item">
        <nav class="navbar navbar-light btn">
        <a class="navbar-brand" href="listardiscos">Ver y modificar discos</a>
        </nav>
    </li>
    <li class="list-group-item">
        <nav class="navbar navbar-light btn">
        <a class="navbar-brand" href="formagregardisco">Agregar nuevo disco</a>
        </nav>
    </li>
    <li class="list-group-item">
        <nav class="navbar navbar-light btn">
        <a class="navbar-brand" href="listarartistas">Ver y modificar artistas</a>
        </nav>
    </li>
    <li class="list-group-item">
        <nav class="navbar navbar-light btn">
        <a class="navbar-brand" href="formagregarartista">Agregar nuevo artista</a>
        </nav>
    </li>
</ul>
<?php require_once 'footer.phtml'?>