<?php require_once 'header.phtml'?>

<ul>
    <li>
        <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="listardiscos">Ver y modificar discos</a>
        </nav>
    </li>
    <li>
        <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="formagregardisco">Agregar nuevo disco</a>
        </nav>
    </li>
    <li>
        <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="listarartistas">Ver y modificar artistas</a>
        </nav>
    </li>
    <li>
        <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="formagregarartista">Agregar nuevo artista</a>
        </nav>
    </li>
</ul>
<?php require_once 'footer.phtml'?>