<?php require 'templates/header.phtml';?>

<h2>Artistas</h2>
<ul class="list-group">
<?php foreach($artistas as $artista): ?>
    <li class="list-group-item disco">
        <div>
            <b><?= $artista->artist_name ?></b> | Fecha de nacimiento: <?=$artista->artist_dob?> | Lugar de nacimiento: <?= $artista->artist_pob?>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> artistas</small></p>

<?php require 'templates/footer.phtml';?>