<?php require 'templates/header.phtml';?>

<ul class="list-group">
    <li class="list-group-item disco">
        <h2>Disco: <?= $disco[0]->album_name ?></h2> 
        <h3>Artista: <?=$disco[0]->artist_name?></h3>
    </li>
    <li class="list-group-item disco">
        <p>Fecha de lanzamiento: <?=$disco[0]->release_date?></p> 
        <p>Duracion: <?=$disco[0]->duration?></p>
    </li>
</ul>


<?php require 'templates/footer.phtml';?>