<?php require 'templates/header.phtml';?>

<h2>Discos</h2>
<ul class="list-group">
<?php foreach($discos as $disco): ?>
    <li class="list-group-item disco">
        <div>
            <b>Disco: <?= $disco->album_name ?></b> | Artista: <?=$disco->artist_name?>
        </div>
        <a href="detalleDiscos/<?php echo $disco->id_album?>"><button class="btn btn-primary mt-2">Ver detalle</button></a>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> discos</small></p>