<?php require 'templates/header.phtml' ?>


<ul class="list-group">
<?php foreach($discos as $disco): ?>
    <li class="list-group-item disco">
        <div>
            <b>Disco: <?= $disco->album_name ?></b> | Artista: <?=$disco->id_artist?> | Fecha de lanzamiento:<?= $disco->release_date?> | Duración:<?= $disco->duration?>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> discos</small></p>


<?php require 'templates/footer.phtml' ?>
