<form>
  <div class="form-group">
    <label for="mailinput">Email address</label>
    <input type="email" class="form-control" id="mailinput" name="mailinput" aria-describedby="emailHelp" placeholder="Ingrese su email">
  </div>
  <div class="form-group">
    <label for="passinput">Contraseña</label>
    <input type="password" class="form-control" id="passinput" name="passinput" placeholder="Ingrese su contraseña">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>