<?php require_once 'templates/header.phtml';?>

<table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Título del disco</th>
                <th scope="col">Fecha de lanzamiento</th>
                <th scope="col">Artista</th>
                <th scope="col">Duración</th>
                <th scope="col">Eliminar</th>
                <th scope="col">Selección</th>
            </tr>
            </thead><?php foreach ($albums as $album) { ?>
                <tr>
                    <td scope="row"><?php echo $album->album_name ?></td>
                    <td scope="row"><?php echo $album->release_date ?></td>
                    <td scope="row"><?php echo $album->artist_name ?></td>
                    <td scope="row"><?php echo $album->duration?></td>
                    <td scope="row">
                        <form method="POST" action="eliminardisco/<?php echo $album->id_album ?>">
                            <button type="submit" class="btn btn-outline-info">Eliminar</button>
                        </form>
                    </td>
                    <td scope="row">
                        <?php if (!$album->selected) { ?>
                            <form method="POST" action="seleccionardisco/<?php echo $album->id_album ?>">
                                <button type="submit" class="btn btn-outline-warning">Agregar a selección</button>
                            </form>
                        <?php } else { ?>
                            <form method="POST" action="deseleccionardisco/<?php echo $album->id_album ?>">
                                <button type="submit" class="btn btn-outline-warning">Quitar de selección</button>
                            </form>
                        <?php } ?>
                    </td>
                    </tr>
            <?php } ?>
        </table>

<?php require 'templates/volverMenuAdmin.phtml';?>
<?php require 'templates/footer.phtml';?>